#!/usr/bin/env bash
# MySQL Configuration Script

# Create MySQL database and user for osTicket
mysql -u root -p <<MYSQL_SCRIPT
CREATE DATABASE osticket;
CREATE USER 'osticket_user'@'localhost' IDENTIFIED BY 'your_password';
GRANT ALL PRIVILEGES ON osticket.* TO 'osticket_user'@'localhost';
FLUSH PRIVILEGES;
MYSQL_SCRIPT

# Update MySQL Configuration (Optional)

sudo sed -i 's/bind-address\s*=\s*127.0.0.1/bind-address = 0.0.0.0/' /etc/mysql/mysql.conf.d/mysqld.cnf
sudo systemctl restart mysql